hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: ''
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - yjk.start_noise=0.5
    - yjk.k_filter=5
    - model_params=hart
    - idx=0,1,2,3
  job:
    name: debug
    chdir: null
    override_dirname: idx=0,1,2,3,model_params=hart,yjk.k_filter=5,yjk.start_noise=0.5
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/server08/yoonjeon_workspace/MMAR/hart
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/server08/yoonjeon_workspace/MMAR/hart/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model_params: hart
      benchmark: geneval
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
benchmark:
  name: geneval
  outdirs: ${home_dir}/geneval/outputs/
  prompts: ${home_dir}/geneval/prompt/evaluation_metadata.jsonl
  batch: 4
  save_as: folder
  model-path: ${home_dir}/geneval/obj_detector/mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.pth
model_params:
  model_name: hart
  use_ema: true
  use_llm_system_prompt: true
  more_smooth: true
  store_seperately: false
  model_path: /home/server08/yoonjeon_workspace/MMAR/hart/ckpts/hart-0.7b-1024px/llm
  text_model_path: /home/server08/yoonjeon_workspace/MMAR/hart/ckpts/Qwen2-VL-1.5B-Instruct
  sample_folder_dir: ./outputs
  max_token_length: 300
  shield_model_path: ./ckpts/shieldgemma-2b
prompt_idx: 0
seed: 42
home_dir: /home/server08/hdd1/yoonjeon_workspace/eval
cfg_scale: 5.0
dynamic_scale: linear
decode: cfg
idx: 0
yjk:
  use_hidden_state_bias: true
  stepsize: 0.025
  update_iters: 10
  do_langevin_dynamics: true
  weight_decay: 0.01
  start_noise: 0.5
  optimizer: AdamW
  k_filter: 5
wandb:
  entity: jeoni
  resume: auto
  project: ${model_params.model_name}
  sweep_name: ${model_params.model_name}
