defaults:
  - benchmark: geneval
  - model_params: showo
  - _self_

  # TRANSFORMERS_CACHE
  # HF_HOME
prompt_idx: 0
seed: 42
home_dir: "/home/server08/hdd1/yoonjeon_workspace/eval"
cfg_scale: 5.0 # 1.0
dynamic_scale: "linear"
decode: cfg
yjk:
  use_hidden_state_bias: true
  stepsize: 0.025
  update_iters: 10
  do_langevin_dynamics: true
  weight_decay: 0.01
  start_noise: 0.5
  optimizer: 'AdamW'
  k_filter: 10

hydra:
  output_subdir: null
  sweep:
    dir: .
    subdir: ""
  run:
    dir: .

wandb:
  entity: "jeoni"
  resume: "auto"
  project: ${model_params.model_name}
  sweep_name: ${model_params.model_name}
